import type { User } from "./user.types";

export const mockUsers: User[] = [
  {
    id: "1",
    fullName: "Sarah Johnson",
    role: "STAFF",
    dateOfBirth: "1990-04-12",
  },
  {
    id: "2",
    fullName: "Michael Brown",
    role: "MEMBER",
    dateOfBirth: "1988-09-25",
  },
  {
    id: "3",
    fullName: "Emma Wilson",
    role: "MEMBER",
    dateOfBirth: "1995-07-14",
  },
  {
    id: "4",
    fullName: "James Taylor",
    role: "STAFF",
    dateOfBirth: "1982-01-08",
  },
  {
    id: "5",
    fullName: "Olivia Martinez",
    role: "MEMBER",
    dateOfBirth: "1999-11-20",
  },
  {
    id: "6",
    fullName: "Daniel Anderson",
    role: "STAFF",
    dateOfBirth: "1985-03-17",
  },
  {
    id: "7",
    fullName: "Sophia Thomas",
    role: "MEMBER",
    dateOfBirth: "1993-06-02",
  },
  {
    id: "8",
    fullName: "William Jackson",
    role: "MEMBER",
    dateOfBirth: "1991-08-28",
  },
  {
    id: "9",
    fullName: "Ava White",
    role: "STAFF",
    dateOfBirth: "1987-12-11",
  },
  {
    id: "10",
    fullName: "Benjamin Harris",
    role: "MEMBER",
    dateOfBirth: "1996-05-09",
  },
  {
    id: "11",
    fullName: "Mia Martin",
    role: "MEMBER",
    dateOfBirth: "1994-02-27",
  },
  {
    id: "12",
    fullName: "Lucas Thompson",
    role: "STAFF",
    dateOfBirth: "1983-09-13",
  },
  {
    id: "13",
    fullName: "Charlotte Garcia",
    role: "MEMBER",
    dateOfBirth: "1997-04-01",
  },
  {
    id: "14",
    fullName: "Henry Martinez",
    role: "STAFF",
    dateOfBirth: "1986-10-19",
  },
  {
    id: "15",
    fullName: "Amelia Robinson",
    role: "MEMBER",
    dateOfBirth: "1998-03-05",
  },
  {
    id: "16",
    fullName: "Alexander Clark",
    role: "MEMBER",
    dateOfBirth: "1992-07-22",
  },
  {
    id: "17",
    fullName: "Evelyn Rodriguez",
    role: "STAFF",
    dateOfBirth: "1981-11-15",
  },
  {
    id: "18",
    fullName: "Michael Lewis",
    role: "MEMBER",
    dateOfBirth: "1990-01-30",
  },
  {
    id: "19",
    fullName: "Harper Lee",
    role: "MEMBER",
    dateOfBirth: "1995-09-07",
  },
  {
    id: "20",
    fullName: "Ethan Walker",
    role: "STAFF",
    dateOfBirth: "1984-06-18",
  },
  {
    id: "21",
    fullName: "Abigail Hall",
    role: "MEMBER",
    dateOfBirth: "1996-12-03",
  },
  {
    id: "22",
    fullName: "Jacob Allen",
    role: "MEMBER",
    dateOfBirth: "1991-05-24",
  },
  {
    id: "23",
    fullName: "Emily Young",
    role: "STAFF",
    dateOfBirth: "1989-08-16",
  },
  {
    id: "24",
    fullName: "Logan Hernandez",
    role: "MEMBER",
    dateOfBirth: "1993-02-10",
  },
  {
    id: "25",
    fullName: "Ella King",
    role: "MEMBER",
    dateOfBirth: "1997-06-29",
  },
  {
    id: "26",
    fullName: "Matthew Wright",
    role: "STAFF",
    dateOfBirth: "1980-04-14",
  },
  {
    id: "27",
    fullName: "Scarlett Lopez",
    role: "MEMBER",
    dateOfBirth: "1994-10-06",
  },
  {
    id: "28",
    fullName: "David Hill",
    role: "MEMBER",
    dateOfBirth: "1992-03-11",
  },
  {
    id: "29",
    fullName: "Grace Scott",
    role: "STAFF",
    dateOfBirth: "1988-07-27",
  },
  {
    id: "30",
    fullName: "Joseph Green",
    role: "MEMBER",
    dateOfBirth: "1999-01-04",
  }
];